version: '3.8'

services:
  bot:
    build: .
    container_name: bot_container
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./src:/app/src
      - ./data:/data

volumes:
  data: